#' Visualize coefficients of variation (CV) distributions
#'
#' Creates two complementary plots to assess the reproducibility of peptide
#' intensity measurements across conditions:
#' \itemize{
#'   \item A **violin + boxplot** showing the distribution of CV values per condition,
#'         with the mean CV marked as a cross (X) and its numeric value displayed.
#'   \item A **bar plot** showing the total number of peptides and the counts of
#'         peptides with CV < 20\% and CV < 5\% (or user-defined thresholds via `scale`).
#' }
#'
#' @param df A data frame containing the CV values and condition labels.
#'   Typically, this is the long‑format output after pivoting the `cv_*` columns
#'   generated by \code{\link{quant_coefVariation}}.
#' @param cond_col Unquoted column name in `df` that defines the experimental
#'   conditions (e.g., "Condition").
#' @param cv_col Unquoted column name in `df` containing the CV values.
#' @param scale Numeric. Either `1` or `100`. If CVs are in percentage
#'   (e.g., 5 for 5\%), use `scale = 1`. If CVs are proportions (e.g., 0.05 for 5\%),
#'   set `scale = 100`. Default is `100`.
#' @param save_plot Logical. If `TRUE`, saves both plots as PNG files in `output_dir`.
#'   Default is `FALSE`.
#' @param output_dir Character. Directory where plots will be saved if `save_plot = TRUE`.
#'   Defaults to the current working directory.
#'
#' @return A list with two components:
#' \item{violin_plot}{A `ggplot` object showing the CV distribution (violin + boxplot).}
#' \item{bar_plot}{A `ggplot` object showing the peptide counts per CV threshold.}
#' If no data is available, both components are `NULL`.
#'
#' @seealso \code{\link{quant_coefVariation}} for calculating CVs from peptide intensities.
#'
#' @importFrom dplyr summarise mutate n
#' @importFrom tidyr pivot_longer drop_na
#' @importFrom scales label_percent
#' @importFrom cli cli_abort cli_alert_warning
#' @import ggplot2
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # -------------------------------------------------------------------------
#' # Typical workflow: calculate CVs (wide), pivot, then plot
#' # -------------------------------------------------------------------------
#'
#' # 1. Calculate CVs using quant_coefVariation() - here with a small synthetic dataset
#' #    (In practice, you would use your own intensity data and metadata.)
#' library(dplyr)
#' library(tidyr)
#'
#' # Example wide-format intensity data (peptides as rows, samples as columns)
#' intensity_data <- data.frame(
#'   sequence = paste0("PEPTIDE", 1:5),
#'   sample1_WT  = c(100, 200, 150, 300, 250),
#'   sample2_WT  = c(110, 190, 160, 290, 260),
#'   sample3_Mut = c(80,  210, 140, 310, 240),
#'   sample4_Mut = c(90,  205, 155, 305, 245)
#' )
#'
#' # Metadata: sample names and their conditions
#' metadata <- data.frame(
#'   SampleName = c("sample1_WT", "sample2_WT", "sample3_Mut", "sample4_Mut"),
#'   Condition = c("WT", "WT", "Mut", "Mut")
#' )
#'
#' # Compute CVs (wide output)
#' cv_wide <- quant_coefVariation(
#'   df = intensity_data,
#'   df_meta = metadata,
#'   int_col = c("sample1_WT", "sample2_WT", "sample3_Mut", "sample4_Mut"),
#'   seq_col = sequence,
#'   ptm_col = NULL,          # no PTM column in this toy example
#'   format = "wide"
#' )
#'
#' # 2. Pivot CV columns into long format for plotting
#' cv_long <- cv_wide |>
#'   dplyr::select(sequence, starts_with("cv_")) |>
#'   tidyr::pivot_longer(
#'     cols = starts_with("cv_"),
#'     names_to = "Condition",
#'     names_prefix = "cv_",
#'     values_to = "CV"
#'   ) |>
#'   tidyr::drop_na(CV)
#'
#' # 3. Plot the CVs
#' cv_plots <- plot_CVs(
#'   df = cv_long,
#'   cond_col = Condition,
#'   cv_col = CV,
#'   scale = 1,        # CVs are already in percent
#'   save_plot = FALSE # set to TRUE to save PNG files
#' )
#'
#' # Display the plots
#' print(cv_plots$violin_plot)
#' print(cv_plots$bar_plot)
#' }
plot_CVs <- \(df, cond_col, cv_col, scale = 100, save_plot = FALSE, output_dir= NULL){

  output_dir <- if (is.null(output_dir)) getwd() else output_dir
  if (!is.null(output_dir) && !dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE)
  }
  # Validate missing arguments
  if (missing(df)) { cli::cli_abort('{.arg df} is missing.') }
  if (missing(cond_col)) { cli::cli_abort('{.arg cond_col} is missing.') }
  if (missing(cv_col)) { cli::cli_abort('{.arg cv_col} is missing.') }

  cond_name <- deparse(substitute(cond_col))
  cv_name <- deparse(substitute(cv_col))

  if (!cond_name %in% names(df)) {
    cli::cli_abort("Column {.val {cond_name}} not found in the dataframe.")
  }
  if (!cv_name %in% names(df)) {
    cli::cli_abort("Column {.val {cv_name}} not found in the dataframe.")
  }


  #account for empty data

  if (nrow(df) == 0) {
    cli::cli_alert_warning("No data to plot CVs – skipping.")
    return(list(violin_plot = NULL, bar_plot = NULL))
  }


  # Compute means per condition
  mean_values <- df |>
    dplyr::summarise(mean_CV = mean({{cv_col}}, na.rm = TRUE),
                     .by = {{cond_col}})

  # Compute bar graph data
  bar_data <- df |>
    tidyr::drop_na({{cv_col}}) |>
    dplyr::summarise(
      `Total ID's` = dplyr::n(),
      `CV < 20%` = sum({{cv_col}} <= (20 * (1/scale)), na.rm = TRUE),
      `CV < 5%` = sum({{cv_col}} <= (5 * (1/scale)), na.rm = TRUE),
      .by = {{cond_col}}
    ) |>
    tidyr::pivot_longer(cols = c(`Total ID's`, `CV < 20%`, `CV < 5%`),
                        names_to = "Metric", values_to = "Count") |>
    dplyr::mutate(Metric = factor(Metric, levels = c("Total ID's", "CV < 20%", "CV < 5%")))  # Ensure correct order


  # Violin + Box Plot
  violin_plot <- ggplot2::ggplot(df, ggplot2::aes(x= {{cond_col}}, y= {{cv_col}}, color = {{cond_col}})) +
    ggplot2::geom_violin(trim = FALSE) +
    ggplot2::geom_boxplot(linewidth = .8, width = .1, ggplot2::aes(color = {{cond_col}})) +
    ggplot2::geom_point(data = mean_values, aes(x = {{cond_col}}, y = mean_CV),
                        shape = 4, size = 3, color = "black") +  # Mean as X marker
    ggplot2::geom_text(data = mean_values, ggplot2::aes(x = {{cond_col}},
                                               y = mean_CV + 0.05,
                                               label = round(mean_CV, 2)),
                       color = "black", size = 5) +  # Mean text above box plot
    ggplot2::scale_color_brewer(palette = "Set1") +
    ggplot2::labs(y= "% CV", x= "") +
    ggplot2::scale_y_continuous(expand = c(0,0),
                                labels = scales::label_percent(scale = scale)) +
    ggplot2::theme_classic(base_size = 16) +
    ggplot2::coord_cartesian(clip = "off") +
    ggplot2::theme(
      legend.position = "none",
      axis.text.x = ggplot2::element_text(size = 16, colour = "black"),
      axis.line.y = ggplot2::element_blank(),
      axis.ticks.y = ggplot2::element_blank(),
      panel.grid.major.y = ggplot2::element_line(linewidth = 1, colour = "grey90")
    )
  if(nrow(bar_data)>0){
  # Bar Plot (Bars closer, X-axis starts from 0)
  bar_plot <- ggplot2::ggplot(bar_data, ggplot2::aes(x = {{cond_col}}, y = Count, fill = Metric)) +
    ggplot2::geom_bar(stat = "identity", position = ggplot2::position_dodge(width = 0.32),
                      width = 0.3) +  # Closer bars
    ggplot2::geom_text(ggplot2::aes(label = Count),
                       position = ggplot2::position_dodge(width = 0.32),
                       vjust = -0.5, fontface = "bold", color = "black", size = 5) +  # Bold black labels on top
    ggplot2::scale_fill_brewer(palette = "Set2") +
    ggplot2::labs(y = "# of Peptides", x = "") +
    ggplot2::coord_cartesian(clip = "off") +
    ggplot2::scale_x_discrete(expand = c(0.3, 0))+
    ggplot2::scale_y_continuous(expand = c(0, 0), limits = c(0, max(bar_data$Count, na.rm = TRUE) * 1.1)) +
    ggplot2::theme_classic(base_size = 16) +

    ggplot2::theme(
      legend.direction = "horizontal",
      legend.position = "bottom",
      legend.title = ggplot2::element_blank(),
      legend.text = ggplot2::element_text(size = 14, colour = "black", face = 'bold'),
      axis.line.y = ggplot2::element_blank(),
      axis.text.y = ggplot2::element_blank(),
      axis.ticks = ggplot2::element_blank(),
      axis.title.y = ggplot2::element_text(size = 16, colour = "black", face = 'bold'),
      axis.text.x = ggplot2::element_text(size = 16, colour = "black", face = 'bold'),
      axis.line.x =  ggplot2::element_line(linewidth = 1.2),
      panel.grid.major.y = ggplot2::element_line(linewidth = 1, colour = "grey90"),
      legend.margin = ggplot2::margin(t = -10, unit = "pt")
    )

  }else{

    bar_plot <- NULL
    cli::cli_alert_warning("No data to create CV bar plot.")

  }


  # save plot -----------------
  if (save_plot) {

    if (!is.null(violin_plot)) {
      ggplot2::ggsave(violin_plot, filename = "CV_Violinplot.png", path = output_dir,
                      dpi = 300, height = 7, width = 6, units = "in", bg = "white")
    }
    if (!is.null(bar_plot)) {
      ggplot2::ggsave(bar_plot, filename = "CV_Barplot.png", path = output_dir,
                      dpi = 300, height = 7, width = 6, units = "in", bg = "white")
    }
  }


  list(violin_plot = violin_plot, bar_plot = bar_plot)


}


